### ISSUE TITLE
Eval?

### ISSUE THREAD

**Issue by ArthurKa** [kaliek/words-to-decimal#1]
https://github.com/kaliek/words-to-decimal/blob/28a1cfa9d02f6347a4d45365e96c3316bd3868ae/src/main.js#L30
https://github.com/kaliek/words-to-decimal/blob/28a1cfa9d02f6347a4d45365e96c3316bd3868ae/src/main.js#L36
https://github.com/kaliek/words-to-decimal/blob/28a1cfa9d02f6347a4d45365e96c3316bd3868ae/src/main.js#L38
https://github.com/kaliek/words-to-decimal/blob/28a1cfa9d02f6347a4d45365e96c3316bd3868ae/src/main.js#L42

Why are there `eval`s? For what reason?

**Comment by kaliek** [comment]
i removed it now
